blog_website/blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('',views.post_list,name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.Post_share, name='post_share'),
    path('<int:post_id>/comment/',views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
]

blog_website/core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
]

blog_website/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Post.Status.PUBLISHED)

    class Status(models.TextChoices):
        DRAFT = 'Draft', 'Draft'
        PUBLISHED = 'Published', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.DRAFT)
    tags=TaggableManager()

    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Custom manager for published posts

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
         return reverse('blog:post_detail',args=[self.publish.year,self.publish.month, self.publish.day,self.slug])
    

class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE,related_name="comments")
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.DateTimeField(default=True)
    

    class Meta:
        ordering=['created']
        indexes=[
            models.Index(fields=['created']),
        ]

    def __str__(self):
       return f'comment by {self.name} on {self.post}'
   
    

blog_website/blog/forms.py
from django import forms
from .models import  Comment


class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class SearchForm(forms.Form):
    query=forms.CharField()


    
    
    

blog_website/blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post, Comment
from .forms import EmailPostForm,CommentForm,SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.contrib.postgres.search import SearchVector
# Create your views here.
def post_list(request,tag_slug=None):
    post_list=Post.published.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        post_list=post_list.filter(tags__in=[tag])
    paginator=Paginator(post_list,3)
    page_number=request.GET.get('page',1)
    try:
        posts=paginator.page(page_number)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'blog/post/posts_list.html',{'posts': posts,'tag': tag})


def post_detail(request, year, month, day, post):
    # Retrieve the post based on the slug
    post = get_object_or_404(Post,status=Post.Status.PUBLISHED,slug=post,
 publish__year=year,
 publish__month=month,
 publish__day=day)
    comments=post.comments.filter()
    form=CommentForm()
    post_tags_ids=post.tags.values_list('id',flat=True)
    similar_posts=Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    context={
        'post':post,
        'comments':comments,
        'form':form,
        'similar_posts':similar_posts

    }

    # Render a template with the post details
    return render(request, 'blog/post/post_detail.html',context)

def Post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
            post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
            f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
            f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
                [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent': sent})

@require_POST
def post_comment(request,post_id):
    post=get_object_or_404(Post,id=post_id,status=Post.Status.PUBLISHED)
    comment=None
    form=CommentForm(data=request.POST)
    if form.is_valid():
        comment=form.save(commit=False)
        comment.post=post
        comment.save()
    return render(request,'blog/post/comment.html',{'post':post,'form':form,'comment':comment})


def post_search(request):
    form = SearchForm()
    query=None
    results=[]
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query=form.cleaned_data['query']
            results=Post.published.annotate(search=SearchVector('title','body'),).filter(search=query)
    return render(request,'blog/post/search.html',{'form': form,
 'query': query,
 'results': results})

blog_website/templates/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    </head>
    <body class="bg-light">
        
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:post_list' %}">My blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:post_list' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "blog:post_search" %}">Search Posts</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <header class="masthead" style="background-image: url('{% static 'img/index.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>My Blog</h1>
                            <span class="subheading">I've Written {% total_posts %} posts so far.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block content %}
        
        {% endblock content %}
        {% include 'partials/pagination.html' with page=posts %}
        {% include 'partials/footer.html' %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

blog_website/templates/blog/post/comment.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add a comment{% endblock %}

{% block content %}
{% if comment %}
<article class="mb-4">
    <div class="container px-4 px-lg-5">
<h2 class="mb-4 class="section-heading"">Your comment has been added</h2>
<div class="d-flex mb-4"><a class="btn btn-primary text-uppercase" href="{{ post.get_absolute_url }}">Back to the Post</a></div>
{% else %}
{% include "blog/post/includes/comment_form.html" %}
{% endif %}
</div>
</article>
{% endblock %}

blog_website/templates/blog/post/includes/comment_form.html
<h2 class="section-heading">Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
    {% csrf_token %}
    {% for field in form %}

    {{ field.errors }}
    <div>
         <label class="form-lable mt-3">{{ field.label_tag }}</label>
    </div>
    {{ field }}
    {% endfor %}
 <p><input class="btn btn-primary text-uppercase" type="submit" value="Add comment"></p>
</form>

blog_website/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a class="text-primary" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
   </ul>

blog_website/templates/blog/post/post_detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}
{% block content %}
<!-- Post Content-->
<article class="mb-4">
    <aside class="float-end pe-5 mt-5"><h3>Similar Posts</h3>
        <ul>
            {% for post in similar_posts %}
            <li>
            <a class="text-primary" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% empty %}
        There are no similar Posts  yet.
            {% endfor %}
           </ul></aside>
    <div class="container px-2">
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-12 col-lg-8 col-xl-7">
                <h3 class="section-heading">{{post.title}}</h3>
                <p>{{post.body}}</p>
                  <p class="fw-bold">  Posted by
                    <a style="text-decoration:none;" class="text-primary" href="#">{{post.author}}</a>
                    &middot; on
                    {{post.publish}}
                </p>
                <p><a class="nav nav-link text-primary" href="{% url "blog:post_share" post.id %}">Share this Post</a></p> 
                {% with comment.count as total_comments %}
                <h2 class="section-heading">
                    {{total_comments}} Comments {{total_comments|pluralize}}
                </h2>
    
                {% endwith %}
                {% for comment in comments  %}
                <p class="fw-bold">
                    Comment {{ forloop.counter }} by <a class="text-primary"style="text-decoration: none;" href="#">{{ comment.name }}</a>
                    {{ comment.created }}
                 </p>
                 {{ comment.body|linebreaks }}
                 {% empty %}
            <p>There are no comments</p>
            {% endfor %}
            <div class="mb-4">{% include "blog/post/includes/comment_form.html" %}</div>
           
            </div>
           
            <div>
                
            </div>
        </div>
    </div>
</article>

{% endblock %}

blog_website/templates/blog/post/posts_list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}

{% block title %}My Blog{% endblock %}
{% block content %}
<aside class="float-end pe-5 mt-5">
    <h3 class="">Latest Posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented posts</h3>
 {% get_most_commented_posts as most_commented_posts %}
 <ul>
 {% for post in most_commented_posts %}
 <li>
 <a class="text-primary" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 </li>
 {% endfor %}
 </ul>
    </aside>
<div class="container px-2">
    <div class="row gx-4 gx-lg-5 ">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% if tag %}
 <h2>Posts tagged with "{{ tag.name }}"</h2>
 {% endif %}
            {% for post in posts %}
            <div class="post-preview">
                <a href="{{ post.get_absolute_url }}">
                    <h2 class="post-title">{{post.title}}</h2>
                    <h3 class="post-subtitle">{{post.body|truncatewords:10|linebreaks}}</h3>
                </a>
                <h6>Tags:<span> {% for tag in post.tags.all %}
                    <a class="text-primary" href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}</span></h6>
                <p class="post-meta">
                    Posted by
                    <a class="text-primary " href="#!">{{post.author}}</a>
                    on {{post.publish}}
                </p>
            </div>
            <hr class="my-4" />
            {% endfor %}
    </div>
</div>
{% endblock %}

blog_website/templates/blog/post/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
 <div class="container px-2">
    <div class="row gx-4 gx-lg-5 ">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% if query %}
 <h2>Posts containing "{{ query }}"</h2>
 {% with results.count as total_results %}
 Found {{ total_results }} result{{ total_results|pluralize }}
 {% endwith %}
            {% for post in results %}
            <div class="post-preview">
                <a href="{{ post.get_absolute_url }}">
                    <h2 class="post-title">{{post.title}}</h2>
                    <h3 class="post-subtitle">{{post.body|truncatewords:10|linebreaks}}</h3>
                    <h6>Tags:<span> {% for tag in post.tags.all %}
                        <a class="text-primary" href="{% url "blog:post_list_by_tag" tag.slug %}">
                        {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}</span></h6>
                    <p class="post-meta">
                        Posted by
                        <a class="text-primary " href="#!">{{post.author}}</a>
                        on {{post.publish}}
                    </p>
                    <hr class="my-4" />
                    {% empty %}
                    <p>There are no results for your query.</p>
                </a>
            {% endfor %}
            <p><a class="text-primary" style="text-decoration:none;" href="{% url "blog:post_search" %}">Search again</a></p>
            {% else %}
 <h1>Search for posts</h1>
 <form method="get">
 {{ form.as_p }}
 <input class="btn btn-primary mb-4" type="submit" value="Search">
 </form>
 {% endif %}
</div>
    </div>
</div>
{% endblock content %}

blog_website/templates/blog/post/share.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Share a Post{% endblock %}
{% block content %}
<article class="mb-4">
    <div class="container px-2">
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% if sent %}
                <h2 class="section-heading">Email sent successfully</h2>
                <p>"{{post.title}} was successfully sent to {{form.cleaned_data.to}}"</p>
                {% else %}
                <h2 class="section-heading">Share "{{post.title}}" by e-mail</h2>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                 <div>
                    {{ field.errors }}
                    <label class="form-lable mt-3">{{ field.label_tag }}</label>
                </div>
                    {{ field }}
                  {% endfor %}
                  <div class="mt-3">
                  <input class="btn btn-primary text-uppercase" type="submit"value="send e-mail"></div>
                </form> 
               
            </div>
        </div>
    </div>
</article>
{% endif %}
{% endblock %}

blog_website/templates/contact/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                <div class="my-5">
                    <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                        <div class="form-floating">
                            <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                            <label for="name">Name</label>
                            <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                            <label for="email">Email address</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                            <label for="phone">Phone Number</label>
                            <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                        </div>
                        <div class="form-floating">
                            <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                            <label for="message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                        </div>
                        <br />
                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3">
                                <div class="fw-bolder">Form submission successful!</div>
                                To activate this form, sign up at
                                <br />
                                <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                            </div>
                        </div>
                        <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                        <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog_website/templates/partials/footer.html
<footer class="border-top">
    <div class="container px-4 px-lg-4">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://twitter.com/home" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com/" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
            </div>
        </div>
    </div>
</footer>

blog_website/templates/partials/pagination.html
<div class="pagination justify-content-end">
    <span class="step-links">
    {% if page.has_previous %}
    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="?page={{ page.previous_page_number }}">Newer Posts →</a></div>
    {% endif %}
    {% if page.has_next %}
    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="?page={{ page.next_page_number }}">Older Posts →</a></div>
    {% endif %}
    </span>
   </div>